POST http://137.204.57.93:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01 23:59:59",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "metadata":{
      "additionalProp1":"http://137.204.57.93:8889/api-docs"
   },
   "providerSystem":{
      "address":"http://137.204.57.93",
      "port": 8888,
      "systemName":"adapter-tester"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"gas-sensor",
   "serviceUri":"gas-sensor-status",
   "version":0
}

################################

POST http://localhost:3334/arrowhead
Content-Type: application/json

{"systemName": "adapter-tester"}

### 

DELETE http://137.204.57.93:8443/serviceregistry/mgmt/3033
Accept: application/json

### 
POST http://137.204.57.93:8443/serviceregistry/query
Content-Type: application/json


{
        "serviceDefinitionRequirement": "gas-sensor"
}

####
POST http://137.204.57.93:8443/serviceregistry/query
Content-Type: application/json

{
  "metadataRequirements": {
    "additionalProp1": "http://137.204.57.93:8889/api-docs"
  }
}

####
GET http://137.204.57.93:8443/serviceregistry/mgmt/3103

###
DELETE http://137.204.57.93:8443/serviceregistry/mgmt/3061
Accept: application/json
