POST http://137.204.57.93:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01 23:59:59",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "metadata":{
      "additionalProp1":"http://137.204.57.93:8889/api-docs"
   },
   "providerSystem":{
      "address":"http://137.204.57.93",
      "port": 8888,
      "systemName":"gas-sensor-status"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"gas-sensor-device",
   "serviceUri":"gas-sensor-status",
   "version":0
}

####
GET http://137.204.57.93:8443/serviceregistry/mgmt/

### 
POST http://177.104.61.116:3334/arrowhead
Content-Type: application/json

{"systemName": "gas-sensor-status"}

###
POST http://192.168.0.19:3333/swagger-petstore/actions/pet
accept: application/json
Content-Type: application/json

{
  "id": 0,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "teste2_ivan",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}

###

POST https://petstore.swagger.io/v2/pet
accept: application/json
Content-Type: application/json

{
  "id": 0,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "teste_ivan",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}

###
PUT https://petstore.swagger.io/v2/pet
accept: application/json
Content-Type: application/json

{
  "id": 9223372000000069000,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "teste3_ivan",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}

###
PUT https://petstore.swagger.io/v2/pet
accept: application/json
Content-Type: application/json

{
  "id": 9223372000000069000,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "teste3_ivan",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}

################################
PUT http://192.168.0.19:3333/swagger-petstore/properties/pet
accept: application/json
Content-Type: application/json

{
  "id": 9223372000000069000,
  "category": {
    "id": 0,
    "name": "string"
  },
  "name": "ivan_093",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "status": "available"
}
################################
GET https://petstore.swagger.io/v2/pet/9223372000000069000

###
POST http://137.204.57.93:8443/serviceregistry/register
Content-Type: application/json

{
   "endOfValidity":"2031-01-01 23:59:59",
   "interfaces":[
      "HTTPS-SECURE-JSON"
   ],
   "metadata":{
      "additionalProp1":"http://localhost:3334/openapi/"
   },
   "providerSystem":{
      "address":"http://localhost",
      "port": 3334,
      "systemName":"wae"
   },
   "secure":"NOT_SECURE",
   "serviceDefinition":"wae",
   "serviceUri":"health",
   "version":0
}

### 
POST http://localhost:3334/arrowhead
Content-Type: application/json

{"systemName": "wae"}

###
GET https://api.apis.guru/v2/list.json
Content-Type: application/json